"use client";
import React, { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ChevronLeft, FileText, Plus, Save, Trash2 } from "lucide-react";
import RestaurantLoader from "@/components/RestaurantLoader";
import { getApiBase } from "@/utils/apiBase";

const inputCls = (err) =>
  `w-full px-4 py-2.5 rounded-xl border ${
    err
      ? "border-red-300 bg-red-50 focus:ring-red-200"
      : "border-gray-300 bg-white focus:ring-indigo-100"
  } focus:outline-none focus:ring-4 focus:border-indigo-500 transition-all text-sm font-medium text-gray-900`;

const blankItem = { desc: "", qty: 1, rate: 0, tax: 18 };
const formatINR = (value) => {
  const n = Number(value || 0) || 0;
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(n);
};

const safeNumber = (v, fallback = 0) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : fallback;
};

export default function EditServiceInvoicePage() {
  const { id } = useParams();
  const router = useRouter();
  const API_BASE = useMemo(() => getApiBase(), []);
  const [loading, setLoading] = useState(false);
  const [booting, setBooting] = useState(true);

  const [clients, setClients] = useState([]);
  const [projects, setProjects] = useState([]);
  const [form, setForm] = useState(null);
  const [errors, setErrors] = useState({});

  useEffect(() => {
    const boot = async () => {
      try {
        const token = localStorage.getItem("authToken") || localStorage.getItem("token");
        const [clientsRes, projectsRes, invoiceRes] = await Promise.all([
          fetch(`${API_BASE}/api/services/clients`, { headers: { Authorization: `Bearer ${token}` } }),
          fetch(`${API_BASE}/api/services/projects`, { headers: { Authorization: `Bearer ${token}` } }),
          fetch(`${API_BASE}/api/services/invoices/${id}`, { headers: { Authorization: `Bearer ${token}` } }),
        ]);

        const [clientsData, projectsData, invoiceData] = await Promise.all([
          clientsRes.json().catch(() => ({})),
          projectsRes.json().catch(() => ({})),
          invoiceRes.json().catch(() => ({})),
        ]);

        setClients(Array.isArray(clientsData.clients) ? clientsData.clients : []);
        setProjects(Array.isArray(projectsData.projects) ? projectsData.projects : []);

        if (invoiceData.success && invoiceData.invoice) {
          const inv = invoiceData.invoice;
          setForm({
            clientId: inv.clientId ? String(inv.clientId) : "",
            projectId: inv.projectId ? String(inv.projectId) : "",
            issuedDate: inv.issuedDate ? new Date(inv.issuedDate).toISOString().split("T")[0] : "",
            dueDate: inv.dueDate ? new Date(inv.dueDate).toISOString().split("T")[0] : "",
            status: inv.status || "Draft",
            discountPercent: Number(inv.discountPercent || 0) || 0,
            notes: inv.notes || "",
            paid: Number(inv.paid || 0) || 0,
            items: Array.isArray(inv.items) && inv.items.length ? inv.items : [{ ...blankItem }],
          });
        } else {
          setForm(false);
        }
      } catch (e) {
        console.error("Failed to load invoice", e);
        setForm(false);
      } finally {
        setBooting(false);
      }
    };
    boot();
  }, [API_BASE, id]);

  useEffect(() => {
    if (!form?.projectId) return;
    const selected = projects.find((p) => String(p.id) === String(form.projectId));
    if (!selected) return;

    setForm((f) => {
      const items = Array.isArray(f.items) && f.items.length ? f.items : [{ ...blankItem }];
      const first = items[0] || { ...blankItem };
      const isAutoGenerated =
        items.length === 1 &&
        (!String(first.desc || "").trim() || String(first.desc || "").startsWith("Project:"));

      if (!isAutoGenerated) return f;

      const newDesc = `Project: ${selected.name || ""}`.trim();
      const newRate = safeNumber(selected.budget, 0);

      if (first.desc === newDesc && safeNumber(first.rate, 0) === newRate) return f;

      return {
        ...f,
        items: [
          {
            ...first,
            desc: newDesc,
            qty: 1,
            rate: newRate,
            tax: safeNumber(first.tax, 18),
          },
        ],
      };
    });
  }, [form?.projectId, projects]);

  const set = (k, v) => {
    setForm((f) => ({ ...f, [k]: v }));
    if (errors[k]) setErrors((prev) => ({ ...prev, [k]: "" }));
  };

  const setItem = (i, k, v) => {
    setForm((f) => {
      const items = [...f.items];
      items[i] = { ...items[i], [k]: v };
      return { ...f, items };
    });
  };

  const addItem = () =>
    setForm((f) => ({ ...f, items: [...f.items, { ...blankItem }] }));
  const removeItem = (i) =>
    setForm((f) => ({ ...f, items: f.items.filter((_, idx) => idx !== i) }));

  const lineTotal = (item) => safeNumber(item.qty, 0) * safeNumber(item.rate, 0);
  const lineTax = (item) => lineTotal(item) * (safeNumber(item.tax, 0) / 100);
  const subtotal = (form?.items || []).reduce((s, it) => s + lineTotal(it), 0);
  const totalTax = (form?.items || []).reduce((s, it) => s + lineTax(it), 0);
  let discPct = 0;
  let discAmount = 0;
  const discountVal = safeNumber(form?.discountPercent, 0);
  if (form?.discountType === "fixed") {
    discAmount = Math.max(0, discountVal);
    discAmount = Math.min(discAmount, subtotal);
    discPct = subtotal > 0 ? (discAmount / subtotal) * 100 : 0;
  } else {
    discPct = Math.min(100, Math.max(0, discountVal));
    discAmount = subtotal * (discPct / 100);
  }
  const grandTotal = Math.max(0, subtotal + totalTax - discAmount);

  const validate = () => {
    const e = {};
    if (!String(form.clientId || "").trim()) e.clientId = "Client is required";
    if (!String(form.projectId || "").trim()) e.projectId = "Project is required";
    if (!form.issuedDate) e.issuedDate = "Issued date is required";
    if (!Array.isArray(form.items) || form.items.length === 0) e.items = "At least one item is required";
    setErrors(e);
    return Object.keys(e).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!validate()) return;

    setLoading(true);
    try {
      const token = localStorage.getItem("authToken") || localStorage.getItem("token");
      const res = await fetch(`${API_BASE}/api/services/invoices/${id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          ...form,
          discountPercent: discPct,
        }),
      });
      const data = await res.json().catch(() => ({}));
      if (data.success) {
        router.push("/services/billing");
      } else {
        alert(data.message || "Error updating invoice");
      }
    } catch (error) {
      console.error("Error updating invoice:", error);
      alert("Failed to connect to server");
    } finally {
      setLoading(false);
    }
  };

  if (booting) return <RestaurantLoader />;
  if (form === false) return <div className="p-6 text-gray-500">Invoice not found.</div>;
  if (!form) return <RestaurantLoader />;

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-20 px-4 sm:px-0">
      <div className="flex flex-col gap-4">
        <button
          onClick={() => router.back()}
          className="flex items-center gap-2 text-gray-500 hover:text-indigo-600 transition-colors w-fit group"
        >
          <ChevronLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          <span className="text-sm font-medium">Back to Billing</span>
        </button>

        <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 bg-white p-6 rounded-2xl border border-gray-200 shadow-sm relative overflow-hidden">
          <div className="flex items-center gap-5 relative z-10">
            <div className="w-14 h-14 rounded-xl bg-indigo-600 flex items-center justify-center text-white shadow-sm">
              <FileText size={24} />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900 tracking-tight">Edit Invoice</h1>
              <p className="text-gray-500 font-medium mt-1 text-sm">
                Update invoice details and line items.
              </p>
            </div>
          </div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">
                  Client <span className="text-red-500">*</span>
                </label>
                <select
                  value={form.clientId}
                  onChange={(e) => set("clientId", e.target.value)}
                  className={inputCls(errors.clientId)}
                >
                  <option value="">Select client...</option>
                  {clients.map((c) => (
                    <option key={c.id} value={c.id}>
                      {c.company} ({c.clientId || c.id})
                    </option>
                  ))}
                </select>
                {errors.clientId && <p className="text-xs font-medium text-red-500">{errors.clientId}</p>}
              </div>
              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">
                  Project <span className="text-red-500">*</span>
                </label>
                <select
                  value={form.projectId}
                  onChange={(e) => set("projectId", e.target.value)}
                  className={inputCls(errors.projectId)}
                >
                  <option value="">Select project...</option>
                  {projects
                    .filter(p => {
                      if (!form.clientId) return true;
                      const selectedClient = clients.find(c => String(c.id) === String(form.clientId));
                      if (!selectedClient) return true;
                      return p.client === selectedClient.company || p.client === selectedClient.clientId;
                    })
                    .map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} ({p.projectId || p.id})
                    </option>
                  ))}
                </select>
                {errors.projectId && <p className="text-xs font-medium text-red-500">{errors.projectId}</p>}
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">
                  Issued Date <span className="text-red-500">*</span>
                </label>
                <input
                  type="date"
                  value={form.issuedDate}
                  onChange={(e) => set("issuedDate", e.target.value)}
                  className={inputCls(errors.issuedDate)}
                />
                {errors.issuedDate && <p className="text-xs font-medium text-red-500">{errors.issuedDate}</p>}
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">Due Date</label>
                <input
                  type="date"
                  value={form.dueDate}
                  onChange={(e) => set("dueDate", e.target.value)}
                  className={inputCls()}
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">Status</label>
                <select value={form.status} onChange={(e) => set("status", e.target.value)} className={inputCls()}>
                  {["Draft", "Sent", "Paid", "Partially Paid", "Overdue"].map((s) => (
                    <option key={s} value={s}>
                      {s}
                    </option>
                  ))}
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">Discount</label>
                <div className="flex gap-2">
                  <select
                    value={form?.discountType || "percent"}
                    onChange={(e) => set("discountType", e.target.value)}
                    className={`${inputCls()} w-16 px-2 text-center`}
                  >
                    <option value="percent">%</option>
                    <option value="fixed">₹</option>
                  </select>
                  <input
                    type="number"
                    min="0"
                    max={form?.discountType === "fixed" ? undefined : "100"}
                    value={form?.discountPercent}
                    onChange={(e) => set("discountPercent", e.target.value)}
                    className={inputCls()}
                    placeholder="0"
                  />
                </div>
              </div>

              <div className="space-y-1.5">
                <label className="text-sm font-semibold text-gray-700">Paid</label>
                <input
                  type="number"
                  min="0"
                  value={form.paid}
                  onChange={(e) => set("paid", e.target.value)}
                  className={inputCls()}
                />
              </div>
            </div>

            <div className="space-y-1.5">
              <label className="text-sm font-semibold text-gray-700">Notes</label>
              <textarea
                value={form.notes}
                onChange={(e) => set("notes", e.target.value)}
                rows={3}
                className={`${inputCls()} resize-none`}
                placeholder="Optional notes to display on invoice..."
              />
            </div>
          </div>

          <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-base font-bold text-gray-900">Line Items</h3>
              <button
                type="button"
                onClick={addItem}
                className="flex items-center gap-2 px-4 py-2 bg-indigo-50 text-indigo-700 border border-indigo-100 rounded-xl text-sm font-semibold hover:bg-indigo-100 transition-colors"
              >
                <Plus size={16} /> Add Item
              </button>
            </div>

            {errors.items && <p className="text-sm font-medium text-red-500">{errors.items}</p>}

            <div className="space-y-3">
              {form.items.map((item, idx) => (
                <div key={idx} className="p-4 rounded-xl border border-gray-200 bg-gray-50/30">
                  <div className="grid grid-cols-1 md:grid-cols-12 gap-3 items-end">
                    <div className="md:col-span-5">
                      <label className="text-xs font-semibold text-gray-600 whitespace-nowrap">Description</label>
                      <input
                        value={item.desc}
                        onChange={(e) => setItem(idx, "desc", e.target.value)}
                        className={inputCls()}
                        placeholder="Work description"
                      />
                    </div>
                    <div className="md:col-span-2">
                      <label className="text-xs font-semibold text-gray-600 whitespace-nowrap">Qty</label>
                      <input
                        type="number"
                        min="0"
                        value={item.qty}
                        onChange={(e) => setItem(idx, "qty", e.target.value)}
                        className={inputCls()}
                      />
                    </div>
                    <div className="md:col-span-2">
                      <label className="text-xs font-semibold text-gray-600 whitespace-nowrap">Rate</label>
                      <input
                        type="number"
                        min="0"
                        value={item.rate}
                        onChange={(e) => setItem(idx, "rate", e.target.value)}
                        className={inputCls()}
                      />
                    </div>
                    <div className="md:col-span-2">
                      <label className="text-xs font-semibold text-gray-600 whitespace-nowrap">Tax %</label>
                      <input
                        type="number"
                        min="0"
                        max="100"
                        value={item.tax}
                        onChange={(e) => setItem(idx, "tax", e.target.value)}
                        className={inputCls()}
                      />
                    </div>
                    <div className="md:col-span-1 flex justify-end">
                      <button
                        type="button"
                        onClick={() => removeItem(idx)}
                        disabled={form.items.length === 1}
                        className="p-2.5 rounded-xl border border-gray-200 text-gray-500 hover:bg-white hover:text-red-600 transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
                        title="Remove"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="bg-white p-6 rounded-2xl border border-gray-200 shadow-sm space-y-4">
            <h3 className="text-base font-bold text-gray-900">Summary</h3>
            <div className="space-y-2 text-sm">
              <div className="flex items-center justify-between">
                <span className="text-gray-500 font-medium">Subtotal</span>
                <span className="font-semibold text-gray-900">{formatINR(subtotal)}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500 font-medium">Tax</span>
                <span className="font-semibold text-gray-900">{formatINR(totalTax)}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-500 font-medium">Discount</span>
                <span className="font-semibold text-gray-900">- {formatINR(discAmount)}</span>
              </div>
              <div className="pt-3 border-t border-gray-100 flex items-center justify-between">
                <span className="text-gray-900 font-bold">Total</span>
                <span className="font-bold text-indigo-700 text-lg">{formatINR(grandTotal)}</span>
              </div>
            </div>

            <div className="pt-4 border-t border-gray-100">
              <button
                type="submit"
                disabled={loading}
                className="w-full py-2.5 bg-indigo-600 text-white rounded-xl font-bold text-sm hover:bg-indigo-700 shadow-sm transition-all active:scale-95 flex items-center justify-center gap-2 disabled:opacity-70"
              >
                {loading ? "Saving..." : (
                  <>
                    <Save size={18} /> Save Changes
                  </>
                )}
              </button>
            </div>
          </div>
        </div>
      </form>
    </div>
  );
}
